---
scripts:
  - name: check_dummy
    path: "demo_scripts/check_dummy"
    output_type: exit_code
  - name: check_google_http
    path: "demo_scripts/check_google_http"
    output_type: exit_code
    override_metric_name: http_site
    labels:
      site_category: search_engine
      protocol: https
      url: www.google.com
  - name: check_google_ping
    path: "demo_scripts/check_google_ping"
    output_type: stdout
    labels:
      site_category: search_engine
      url: www.google.com
  - name: check_system_load
    path: "demo_scripts/check_system_load"
    output_type: "multi_metric"
    metrics_regex: ".*load\\s+averages:\\s+(?P<load1min>\\d*\\.?\\d*)\\s+(?P<load5min>\\d*\\.?\\d*)\\s+(?P<load15min>\\d*\\.?\\d*).*"
    labels:
      server_type: web